name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  23ds1000022@ds.study.iitm.ac.in
        uses: actions/checkout@v3

      - name:  23ds1000022@ds.study.iitm.ac.in
        run: ./deploy.sh
